project:
  type: book

book:
  title: "Data mining with {tidymodels}"
  author: "Youngrok Lee"
  date: today
  chapters:
    - index.qmd
    - ch02_regression.qmd
    - ch03_regularized_regression.qmd
    - ch04_dimension_reduction.qmd
    - ch05_classification.qmd
    - ch06_logistic_regression.qmd
    - ch07_da.qmd
    - ch08_tree.qmd
    - ch09_svm.qmd
    - ch10_ensemble.qmd
    - ch11_cluster.qmd
    - ch12_hierarchical_clustering.qmd

format:
  html:
    theme: cosmo



