project:
  type: book

book:
  title: "Data mining with {tidymodels}"
  author: "Youngrok Lee"
  date: "6/15/2024"
  chapters:
    - index.qmd
    - ch02_regression.qmd
    - ch03_regularized_regression.qmd
    - ch04_dimension_reduction.qmd

format:
  html:
    theme: cosmo



